default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

prod_common: &prod_common
  adapter:  mysql2
  host:     127.0.0.1
  pool:     30
  timeout:  5000
  username: fgsf-user
  password: <%= YAML.load_file(SECRET_PATH)['database_password'] rescue 'default' %>

production:
  <<: *prod_common
  database: fgsf_dev
