# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0805133fcad853b0b056ed46572749e9aa306ddadd3041fef529c0657567009fe8c451f436b4138cb87f15279920c0f1559dedab4655ad058dd7c4acb7db2a3a

test:
  secret_key_base: 8ceb05cc8b1b681222aa276162de4a77caa585ed8a9f6b02eddc12b3775251e31e29eb3413a1c3d4e02e399e64953e7af52d361499841edff287542212305919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_token: <%= SecureRandom.hex %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
